---
- name: Fabric building
  hosts: all
  become: true

  tasks:

    - include_tasks: tasks/configuring_interfaces.yml

    - include_tasks: tasks/install_frr_servers.yml
      when: "'servers' in group_names"

    - include_tasks: tasks/bgp_config.yml