---
- name: Activating bgp + zebra daemons
  template: 
    src: templates/daemons
    dest: /etc/frr/daemons

- name: Adding BGP config 
  template: 
    src: templates/bgp.j2
    dest: /etc/frr/frr.conf

- name: Restart frr service
  service: 
    name: frr
    state: restarted