---
- name: Activating bgp + zebra daemons
  template: 
    src: daemons
    dest: /etc/frr/daemons

- name: Adding BGP config 
  template: 
    src: bgp.j2
    dest: /etc/frr/frr.conf
  notify: Restart frr service
