---

- name: Get eth0 facts
  setup:
    gather_subset:
      - network

- name: Add network interfaces
  template: 
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: Flushing previous configurations
  shell: ip addr flush dev "{{ item.name }}" && ifup "{{ item.name }}" --force
  with_items: 
    - "{{ interfaces }}"
  ignore_errors: yes

  #- name: Restart networking service
  #  service: 
  #    name: networking
  #    state: restarted
  #    sleep: 3 # This sleep is a workaround because ansible drop the connection when network is restarted sometimes... (see here : https://docs.ansible.com/ansible/latest/modules/service_module.html)

  # /!\ Using Service module use systemd under the hood
  # Systemd doesn't support sleep option so there is a chance that ansible drop the connection...
  # As a workaround, we have to use a shell command that adds a sleep.
  #
- name: Enforce DNS
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: nameserver {{ ansible_facts.eth0.ipv4.address.split('.')[:-1] | join('.') }}.1

- name: Remove default CITC eth0 file
  file:
    path: /etc/network/interfaces.d/eth0.cfg
    state: absent

- name: Kill dhclient
  shell:
    cmd: killall dhclient
  ignore_errors: yes

- name: Bouncing ifaces
  shell: ifdown "{{ item.name }}" --force && ifup "{{ item.name }}" --force
  with_items: 
    - "{{ interfaces }}"
  ignore_errors: yes

  #- name: Restart networking service [CumulusLinux devices]
  #  shell:
  #    cmd: "ifreload -a ; sleep 10"
  #  when: "'fabric' in group_names"

- name: Tries to resurrect dead hosts
  meta: clear_host_errors
