---
- name: set an empty list named ips
  set_fact:
    ips: []

- name: append all known IPv4 addresses from the group network
  set_fact:
    ips: "{{ ips + [item] }}"
    #with_inventory_hostnames: servers
  loop: "{{ lookup('subelements', groups['servers'], 'ansible_lo_1.ipv4.address', errors='warn') }}"

- name: ping all IP addresses in ips
  shell: "ping {{ item }} -c 1"
  with_items:
    - "{{ ips }}"
  register: result
  changed_when: "result.rc != 0"
