---
- name: Get FRR
  get_url:
    url: {{ item }}
    dest: /tmp/
  with_items: 
    - https://github.com/FRRouting/frr/releases/download/frr-6.0/frr_6.0-1.ubuntu16.04+1_amd64.deb
    - https://github.com/FRRouting/frr/releases/download/frr-6.0/frr-pythontools_6.0-1.ubuntu16.04+1_all.deb
      #- https://github.com/FRRouting/frr/releases/download/frr-6.0/frr_6.0-1.ubuntu18.04+1_amd64.deb
      #- https://github.com/FRRouting/frr/releases/download/frr-6.0/frr-pythontools_6.0-1.ubuntu18.04+1_all.deb
  when: "'servers' in group_names"

- name: Install dependencies
  apt:
    name: {{ item }}
  with_items:
    - libc-ares2
    - libsensors4
    - libsnmp-base 
    - libsnmp30
    - python-ipaddr
  when: "'servers' in group_names"

- name: Install FRR
  apt:
    deb: /tmp/{{ item }}
  with_items:
    - frr_6.0-1.ubuntu16.04+1_amd64.deb
    - frr-pythontools_6.0-1.ubuntu16.04+1_all.deb
  when: "'servers' in group_names"
