---
#- name: Get facts about the servers to have access to ansible_distribution_release
#  setup:
#    filter:
#      - "ansible_distribution_release"

- name: Install dependencies
  apt:
    pkg:
      - libc-ares2
      - libsensors4
      - libsnmp-base 
      - libsnmp30
      - python-ipaddr
    state: present
  when: "'servers' in group_names"

# New way to install now that FRR has deb repo
- name: Add an FRR repo signing key
  apt_key:
    url: https://deb.frrouting.org/frr/keys.asc
    state: present

- name: Add the FRR repo
  apt_repository:
    repo: "deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable"
    state: present

- name: Actually install FRR from the repo
  apt:
    update_cache: yes
    pkg:
      - frr
      - frr-pythontools
