---
#- name: Get facts about the servers to have access to ansible_distribution_release
#  setup:
#    filter:
#      - "ansible_distribution_release"

- name: Kill dhclient
  shell:
    cmd: killall dhclient
  ignore_errors: yes

- name: Disable systemd-resolved
  shell:
    cmd: systemctl stop systemd-resolved ; systemctl disable systemd-resolved

- name: Enforce DNS
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: nameserver {{ ansible_facts.eth0.ipv4.address.split('.')[:-1] | join('.') }}.1

- name: Remove default CITC eth0 file
  file:
    path: /etc/network/interfaces.d/eth0.cfg
    state: absent

- name: Install dependencies
  apt:
    pkg:
      - libc-ares2
      - libsensors4
      - libsnmp-base 
      - libsnmp30
      - python-ipaddr
    state: present
  when: "'servers' in group_names"

# New way to install now that FRR has deb repo
- name: Add an FRR repo signing key
  apt_key:
    url: https://deb.frrouting.org/frr/keys.asc
    state: present

- name: Disable netq repo since it doesn't support i386 anymore
  apt_repository:
    repo: "deb http://apps3.cumulusnetworks.com/repos/deb bionic netq-latest"
    state: absent

- name: Add the FRR repo
  apt_repository:
    repo: "deb [trusted=yes] https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable"
    state: present

- name: Actually install FRR from the repo
  apt:
    update_cache: yes
    pkg:
      - frr
      - frr-pythontools
